require('dotenv').config();
const express = require("express");
const bodyParser = require("body-parser");
var mysql = require("mysql");
const nodemailer = require("nodemailer");

const app = express();

const sqlemails = 'SELECT mail FROM usersinfo';
const countRows = 'SELECT COUNT(*) as total FROM usersinfo';
var rowNumber;
var mail_list = [];


app.use(express.static("public"));  //To use local assets
app.use(bodyParser.urlencoded({extended: true}));

app.get("/nodeapp",function(req,res){
    res.sendFile(__dirname + "/form.html");
});

app.listen(function(){
    console.log("app started....");
});

var connection = mysql.createConnection({
    host: 'localhost',
    port: 3306,
    user: process.env.DB_USER,
    password: process.env.DB_PASS,
    database: 'busihfkl_formmysqlwithnodejs'
});



//ensure database is running
connection.connect(function(err){
    if(err) throw err;
    else{
        console.log('Database is connected successfully...');
    }
    
});

//counting rows in database
connection.query(countRows,function(err,data){
    if(err){
        console.log('Catched errors '+err);
    }
    else{
        rowNumber = data[0].total;
        console.log('You have '+rowNumber+' rows in table');
    }
});

app.post("/nodeapp",function(req,res){
    var firstName = req.body.firstName;
    var lastName = req.body.lastName;
    var username = req.body.username;
    var email = req.body.email;
    var phone = req.body.phone;
    var gender = req.body.gender;

    console.log(firstName,lastName,username,email,phone,gender);
    
    //res.send(req.body);
    
    var sql = "insert into usersinfo values('"+firstName+"', '"+lastName+"', '"+username+"','"+email+"', '"+phone+"', '"+gender+"')";
    
    
    connection.query(sql, function (err) {
        if (err){
            res.sendFile(__dirname + "/fail.html");
            console.log(err);
        }
        else{
            res.sendFile(__dirname + "/success.html");
        }
        
    });
      
    //Email fetch from database
    connection.query(sqlemails, function(err, email, fields){
        for(var k in email){
            mail_list.push(email[k].mail);
        }
        
        console.log("You have "+ mail_list.length+" mails in the database");
    
    //Scrapping condition here
        if(mail_list.length > 4){
            console.log("You have enough mail to send email");
            sendMailFinal();
        }
        else{
            console.log("You don't have enough mail to send email");
        }
      });


    //connection.end();

});



var transporter = nodemailer.createTransport({
    service: 'gmail',
    auth:{
        user: process.env.EMAIL,
        pass: process.env.PASSWORD
    }
});

var mailOptions = {
    from: 'Mirror <donationdistributation@gmail.com>',
    to: mail_list,
    subject: 'No-Reply',
    text: 'This is an autogenerated mail from my newly build web-application. Do not reply the mail.'

};

sendMailFinal = function(){
    transporter.sendMail(mailOptions,function(err,data){
        if(err){
            console.log("Send Faild. reason: "+err);
        }
        else{
            console.log("Mail send successfully");
        }
    });
}








